# Generated by Django 4.0.4 on 2022-05-13 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='courses',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.courses'),
        ),
    ]
