# Generated by Django 4.0.4 on 2022-05-16 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_myuser_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='uuid',
            new_name='id',
        ),
    ]
