# Generated by Django 4.0.4 on 2022-05-17 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_rename_id_address_uuid'),
        ('accounts', '0005_myuser_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='id',
            new_name='uuid',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='address.address'),
        ),
    ]
