# Generated by Django 4.0.4 on 2022-05-16 20:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_alter_courses_instructor_remove_courses_students_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='uuid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='courses',
            name='students',
            field=models.ManyToManyField(related_name='student', to=settings.AUTH_USER_MODEL),
        ),
    ]
