# Generated by Django 4.0.4 on 2022-05-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
