# Generated by Django 4.0.4 on 2022-05-17 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_alter_address_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='id',
            new_name='uuid',
        ),
    ]
